name: Fund Daily Sync

on:
  schedule:
    - cron: '0 13 * * *' # 北京时间每天 21:00 自动运行
  workflow_dispatch:      # 允许手动点火

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Spider and Report
        run: |
          python program/fund_db_manager.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          
          # 设置北京时间
          export TZ='Asia/Shanghai'
          CUR_TIME=$(date "+%Y-%m-%d %H:%M")
          
          git add .
          # 如果没有变化则跳过，如果有变化则使用中文 Commit
          git commit -m "自动更新 | $CUR_TIME | 数据库已同步" || exit 0
          git push
