name: Fund Daily Sync

on:
  schedule:
    - cron: '0 13 * * *' # 北京时间每天晚上 21:00 运行
  workflow_dispatch:      # 允许你手动点击按钮运行测试

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Spider
        run: |
          # 关键：根据你之前的清单，脚本在 program 文件夹下
          python program/fund_db_manager.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add .
          # 使用 $(date) 获取当前时间并放入 commit 信息
          CURRENT_TIME=$(date "+%Y-%m-%d %H:%M:%S")
          git commit -m "自动同步 | $CURRENT_TIME | 检查并更新净值" || exit 0
          git push
